// <auto-generated />
namespace ConsoleTester.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Splitted_PermissionSetting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Splitted_PermissionSetting));
        
        string IMigrationMetadata.Id
        {
            get { return "201410231254371_Splitted_PermissionSetting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
